### ISSUE TITLE
Current setup name location

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-core#109]
@tpietzsch 

Any chance it could become an option in the `Prefs` that the current setup name is left bound rather than centred?
This would avoid in many cases the crash with the time point information:

![image](https://user-images.githubusercontent.com/2157566/93590088-352d2c00-f9ae-11ea-875d-fb165b8d325f.png)

**Comment by tpietzsch** [comment]
Sure, feel free to add it!

**Comment by tischi** [comment]
@tpietzsch I created a PR (see above). Let me know what you think.
