### ISSUE TITLE
Change name of TransformedSource during construction

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-core#124]
Hi @tpietzsch @axtimwalde @tinevez,
(cc @NicoKiaru)

It would be very useful for me if I could change the name of a Source when transforming it.

I would thus like to add constructors to `TransformedSource` that accept a `String name`.

And then I would change:

```
	@Override
	public String getName()
	{
		return source.getName();
	}
```

to 

```
	@Override
	public String getName()
	{
		if ( name != null ) return name;
		else return source.getName();
	}
```

Would you accept a PR that does that?

**Comment by tpietzsch** [comment]
closed via #127
