### ISSUE TITLE
zero value always shown as black even for signed int source

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-core#126]
Hi,

I have a source (N5) which is normalized signed int data. BDV displays it just fine and also contrast adjustment works.
However, the zero value is always mapped to appear as black, even though the minimum selector is set to a negative value. This leads to black contour lines in the displayed data.

**Comment by martinschorb** [comment]
![Screenshot 2021-06-18 at 16 02 46](https://user-images.githubusercontent.com/35071867/122573081-b05f6380-d04e-11eb-9997-b7a55e98a3ab.png)

**Comment by tpietzsch** [comment]
Can you share a test data set to reproduce?
Also, is this in vanilla BDV or MoBIE Viewer or something similar? (It could be that this is some custom source blending code)

**Comment by martinschorb** [comment]
Hi,

yes, you are right:
- vanilla BDV: manually adjusting levels to -127/+127 gives good results
- BDV-Playground : 
-- original BDV - correct behaviour, 
-- BDVPG mixed projector - contour lines
-- BDVPG Sum projector - contour lines
-- BDVPG Average projector - contour lines
- MoBIE - contour lines

I guess @NicoKiaru , this one's for you then...

**Comment by martinschorb** [comment]
Test data:

[BDV_testzero.zip](https://github.com/bigdataviewer/bigdataviewer-core/files/6688723/BDV_testzero.zip)

supposed to show nice gradients from -20 to +20 intensity.

**Comment by NicoKiaru** [comment]
Mapping 'zero' as black or actually transparent has been a trick used to handle transparency, but I've added a way to handle better transparency, and also 'layers', but at the cost of speed ( see https://github.com/NicoKiaru/bigdataviewer-playground-display). Also, now the 'default' bdv used in bdv-playground is flexible. It can be the vanilla one, the [mobie one](https://github.com/NicoKiaru/bigdataviewer-playground-display/tree/master/src/main/java/sc/fiji/bdvpg/bdv/supplier/mobie), the ['transparent' one](https://github.com/NicoKiaru/bigdataviewer-playground-display/tree/master/src/main/java/sc/fiji/bdvpg/bdv/supplier/alpha), the [biop one](https://github.com/NicoKiaru/bigdataviewer-playground-display/tree/master/src/main/java/sc/fiji/bdvpg/bdv/supplier/biop). Each of these have different features enabled by default. If @tischi wants to provide a different one, he can also do this on mobie's repo.

All of this is not currently on the update site of bdv-pg. This week I hope to release it, and I think @tischi is ready for it ?

Cheers

**Comment by tischi** [comment]
> This week I hope to release it, and I think @tischi is ready for it ?

I think I tried it and it worked for me.
