### ISSUE TITLE
Bug report: Fiji crashes when resaving to .tiff

### ISSUE THREAD

**Issue by schmiedc** [bigdataviewer/bigdataviewer-core#13]
Hi Tobias,

I want to resave an HDF5 dataset into .tiff. But Fiji keeps on crashing after about 16-18 time points. Fiji in this case just closes without error message. When I look into the system monitor the memory runs full during resaving and then Fiji closes. 

Possibly a memory leak?

Settings tested for resaving: 

I use ArrayImg (faster) as ImgLib2 container. Without lossless compression of the TIFF files. The resulting .tiff files are 3.3GB in size. I tried it twice with these settings.

Then I tried it once with CellImg ImgLib2 container again without lossless compression of the TIFF files. Then it failed after resaving 24 files. 

Dataset: 
The dataset is a fused (average fusion) HDF5 dataset with 85 time points. Each .h5 file is 1.5 GB in size as HDF5 and 3.3GB as TIFF. The last few time points of the datasets are only 1.4 GB and on 1.2 GB which is a bit weird but for the BigDataViewer it works. The dataset sits on tomancak-pc-15. 

Fiji: 
I use the latest Fiji (imagej v1.50b) and updated the plugins. 
spimdata version: 0.9-revision
spimreconstruction version 2.4.2

I can send you the xml per Email if you want.

Cheers,
Christopher

**Comment by tpietzsch** [comment]
shouldn't this issue be in SPIMRegistration?

**Comment by schmiedc** [comment]
Hi Tobias,

Ok, true the resaving is done via the Multiview Reconstruction plugin. 
I will transfer it there. 

Cheers,
Christopher
