### ISSUE TITLE
Two-way support for Imaris?

### ISSUE THREAD

**Issue by emmenlau** [bigdataviewer/bigdataviewer-core#15]
This might have come up before, please excuse if I'm ignorant of a prior discussion of the topic.
I very much like the open BigDataViewer HDF5 format. However many of our users still often use
commercial software like Imaris. Since the two file formats are relatively similar, I was wondering if
there could be real two-way support?

I know that Imaris can read BDV HDF5, but they will convert the file into IMS format, so its
(a) cumbersome and (b) irreversible. I also know that BDV has experimental support for display
of Imaris files, but I would prefer my standard file format to be the (open) BDV HDF5 over IMS.
To get the best of both worlds, would it be possible that BDV adds the Imaris required internal
structure so that Imaris would natively open the file? I don't know all the details, but I assume
that by using HDF5 internal links, it might be possible to avoid any data duplication?

**Comment by rmd06** [comment]
I have write a script to make ims file de novo from matrix

**Comment by tinevez** [comment]
@emmenlau I think that this responsibility is in the end of the Imaris people, not the BDV people.
Therefore, can I close this issue here?
