### ISSUE TITLE
Improve support for short data type in xml/hdf5 

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-core#154]
See discussion here: https://imagesc.zulipchat.com/#narrow/stream/327326-BigDataViewer/topic/XML.2FHDF5.20specification

Here is a dataset that was stored in python as `unsigned short` (Corrected).
The data was rescaled such that the min and max values should be 0 and 65535.
https://oc.embl.de/index.php/s/BvxrscO9bxPf4No

**Comment by mkitti** [comment]
tracking

**Comment by mkitti** [comment]
Do we want a signed or unsigned uint16?

**Comment by constantinpape** [comment]
> Here is a dataset that was stored in python as `short`.

The dataset you have provided here as stored as **unsigned** short. (I think this is actually what you want, but it's confusing that you write short).

Here's the details for one of the datasets:
```
/t00000/s00/0/cells      Dataset {750/750, 551/551, 699/699}
    Location:  1:3896
    Links:     1
    Chunks:    {64, 64, 64} 524288 bytes
    Storage:   577723500 logical bytes, 372274970 allocated bytes, 155.19% utilization
    Filter-0:  deflate-1 OPT {4}
    Type:      native unsigned short
```

**Comment by mkitti** [comment]
Have you tried to load this via n5-viewer?

https://www.youtube.com/watch?v=nYzYiXi0sYs&t=165s

**Comment by tischi** [comment]
> The dataset you have provided here as stored as unsigned short. (I think this is actually what you want, but it's confusing that you write short).

Sorry, yes, I corrected the description.

**Comment by tpietzsch** [comment]
#157 addresses this issue. Could you have a look?
@tischi @StephanPreibisch
