### ISSUE TITLE
Support for channels that only exist for part of the time range?

### ISSUE THREAD

**Issue by janroden** [bigdataviewer/bigdataviewer-core#168]
Does BDV currently support image data / metadata where some channels only exist for part of the full time range (i.e., for a subset of all time points)?

If so, what would a minimal-example `.xml`  file for such a situation look like? 

I was wondering whether this could be achieved by having `ViewRegistration` blocks for only a subset of the time points? 
Or are those intended only for affine transforms changing over time, but there have to be `ViewRegistration` blocks present for all​ time points?

If this isn't supported yet, would support for this be planned / in scope for one of the next releases?

Thanks a lot!

**Comment by tpietzsch** [comment]
Yes, that's possible.
I don't have a minimal xml file at hand, but it's straightforward: In the ` <SequenceDescription>...</SequenceDescription>` section of the XML, add a `<MissingViews>` tag, e.g.,
```
<MissingViews>
   <MissingView timepoint="0" setup="1" />
   <MissingView timepoint="0" setup="2" />
   <MissingView timepoint="1" setup="1" />
   <MissingView timepoint="1" setup="2" />
   <MissingView timepoint="2" setup="2" />
   <MissingView timepoint="3" setup="2" />
</MissingViews>
```
etc. That is, just list the missing views.

**Comment by janroden** [comment]
That's great :-) 
Thanks a lot for the fast response and the example!
