### ISSUE TITLE
Deadlock when rearranging MinMaxGroups

### ISSUE THREAD

**Issue by igorpisarev** [bigdataviewer/bigdataviewer-core#24]
This is the follow-up on https://github.com/bigdataviewer/bigdataviewer-core/issues/23
I used a hack in order to be able to specify different display ranges for different sources. After constructing the BigDataViewer I rearragned the min-max groups to the desired configuration.

What I found is that every other time it deadlocks within the removeSetupFromGroup() call during repainting the brightness dialog.
Here is the stack trace: http://pastebin.com/nTA6hcu6

Calling this method on the Event Dispatcher thread solves the issue. It would be more convenient if the brightness dialog ensured correct threading by itself.

**Comment by tpietzsch** [comment]
Thanks for reporting, @igorpisarev.

> Calling this method on the Event Dispatcher thread solves the issue. It would be more convenient if the brightness dialog ensured correct threading by itself.

absolutely correct. I'll fix it.

**Comment by tpietzsch** [comment]
@igorpisarev hmm, actually this should already be fixed in the latest release (3.0.0).

https://github.com/bigdataviewer/bigdataviewer-core/blob/master/src/main/java/bdv/tools/brightness/BrightnessDialog.java#L113-L127

Can you try whether the problem persists with 3.0.0 or master.

**Comment by igorpisarev** [comment]
Thanks @tpietzsch, I somehow didn't notice that it was already fixed.
Tested it with 3.0.0 and it works properly.
