### ISSUE TITLE
Move stuff from the net.imglib2 package to imglib2

### ISSUE THREAD

**Issue by tpietzsch** [bigdataviewer/bigdataviewer-core#28]

**Comment by axtimwalde** [comment]
Is this the right time? Now that the primitive `VolatileTypes` are complete, we can move them.  That would also enable us to move `VolatileTypeMatcher` into ImgLib2 which would save me from waiting for a bigdataviewer-core release before I can fix this pull request https://github.com/bigdataviewer/bigdataviewer-vistools/pull/13 which would enable me to slowly get out of my current SNAPSHOT dependency hell :).

**Comment by tpietzsch** [comment]
@axtimwalde I would package this with pending changes to the ImgFactory and move of VolatileTyptes to a different package (simplifies some internals) which will be both breaking changes. I'm on vactaion already, it will have to wait until next year

**Comment by axtimwalde** [comment]
Great! Just wanted to use the moment to bump this :).  Happy holidays!

**Comment by tpietzsch** [comment]
I'm on this now. As mentioned above, I want to move the volatile types to a different package; Specifically, to the same package as the non-volatile variant. So `VolatileIntType` moves to `net.imglib2.type.numeric`. This allows to get rid of the additional wrapping layer, see this commit https://github.com/bigdataviewer/bigdataviewer-core/commit/d2556705dd7a0ff9fed1190bc7abe38b64ee445d
There will be some fall-out because whoever uses volatile types needs to fix their imports. But I think it should be limited to a few people and easy to fix.
If we want do this, I would do it now, because with `NativeType` and `ImgFactory` changes we need to do a major version bump to `imglib2-5.0.0` anyway.

I think it's worth doing. Opinions, objections? @axtimwalde, @StephanPreibisch, @ctrueden

**Comment by axtimwalde** [comment]
+1

**Comment by StephanPreibisch** [comment]
+1

**Comment by ctrueden** [comment]
:+1:

**Comment by hanslovsky** [comment]
I am all for it, too.
