### ISSUE TITLE
Missing compression information on Arxiv Paper

### ISSUE THREAD

**Issue by Xqua** [bigdataviewer/bigdataviewer-core#42]
Dear, 

I am writting my own script to create XML/HDF5 files in python (need to use on a cluster, on single plane tiff, so the IJ implementations aren't going to work for me) 

I succeeded in doing so, BUT, I am missing the compression part. 
on the Archive paper, it states that it uses the DEFLATE compression, which is basically gzip. 
But there is no indication on the level of compression available ? 
is it 0 or 9?

Thanks !

**Comment by tpietzsch** [comment]
Looking into the code, it just uses the default compression level of  the jhdf5 library, here

https://github.com/bigdataviewer/bigdataviewer-core/blob/8b6b8c2f250a02b6666e19a51dd9836bd3de4731/src/main/java/bdv/export/WriteSequenceToHdf5.java#L603

which is 6

http://svnsis.ethz.ch/doc/hdf5/current/constant-values.html#ch.systemsx.cisd.hdf5.HDF5IntStorageFeatures.DEFAULT_DEFLATION_LEVEL

But you could compress with whatever level you want of course. It shouldn't make a difference when reading the files...

**Comment by Xqua** [comment]
Thanks for this info !
