### ISSUE TITLE
range overflow in trilinear interpolator

### ISSUE THREAD

**Issue by axtimwalde** [bigdataviewer/bigdataviewer-core#6]
I just noticed that both CATMAID and Openconnectome backends show value range overflow artifacts
when trilinear interpolation is switched on.  Reason is probably that UnsignedByteType or ARGBType are
directly used by NLinearInterpolator.  I remember that we had addressed this at some point using NLinearInterpolatorARGB (which wouldn't solve the UnsignedByteIssue) but cannot remember whether that was in this project or one of its predecessors.

**Comment by tpietzsch** [comment]
@axtimwalde The issue should be fixed with commit bd513e5419bd878be54574855e7705fded3b2aff. Can you confirm?

**Comment by tpietzsch** [comment]
@axtimwalde Argh. That didn't compile. Now? 4c7e2f59a4a14c80521075697924e345b4e234fa

**Comment by axtimwalde** [comment]
Thanks!  Works beautifully.
