### ISSUE TITLE
Get nonVolatile access on VolatileSpimSource

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-core#60]
Hi @tpietzsch,

Looks like you changed the API of `VolatileSpimSource`, removing the `nonVolatile()` method:
https://github.com/bigdataviewer/bigdataviewer-core/commit/75e082a6686e6d980215c1550394fc4bedf6d702#diff-8108dedc15fa29afec4e4c00046d1b09L71

Is there still a way to get `nonVolatile` access to the image data? 
The code where, I think, I need it currently looks like this: https://github.com/tischi/bdv-utils/blob/master/src/main/java/de/embl/cba/bdv/utils/BdvUtils.java#L774

Probably my code is kind of dumb anyway, but I did not know how to achieve it in a better way...

**Comment by tpietzsch** [comment]
Where does the `Source` come from?
Normally, if you get the list of Sources from `ViewerState.getSources()`, these will be the non-volatile sources, with the volatile versions nested underneath
https://github.com/bigdataviewer/bigdataviewer-core/blob/6d32df2f4fa849fdbd4b1ad9251a08376e3c82ab/src/main/java/bdv/viewer/SourceAndConverter.java#L96-L99

Only if there is no non-volatile version, the `ViewerState.getSources()` contains sources that are `VolatileSpimSource` directly. And then there is no non-volatile version anyway.

I guess this is about `LazySpimSource`. I think you probably initialize/add that to BDV in an unintented way. Ideally you would have a `LazySpimSource` and a `VolatileLazySpimSource` that is nested underneath. For drawing, the BDV will check whether there is a volatile version of the source, but not vice versa. So, for example, the volatile version of your LazySpimSource would be used for rendering movies, leading to a lot of black...

See https://github.com/bigdataviewer/bigdataviewer-core/blob/6d32df2f4fa849fdbd4b1ad9251a08376e3c82ab/src/main/java/bdv/BigDataViewer.java#L251-L284 for how the BDV sets up a volatile/non-volatile `SourceAndConverter` pair.

**Comment by tischi** [comment]
Thanks a lot for the detailed answer!

In fact, it might be historical that I needed the `VolatileSpimSource.nonVolatile()` method. 
I am not sure it is currently still needed; I changed my code to throw an error in case it ends up there.

The way I currently initialise the `LazySpimSource` is like this: https://github.com/tischi/bdv-utils/blob/master/src/main/java/de/embl/cba/bdv/utils/sources/LazySpimSource.java#L53
This uses exactly the methods you pointed out above, so I guess that should be OK?

**Comment by tpietzsch** [comment]
Looks OK, yes 👍
