### ISSUE TITLE
Constructor of BigDataViewer is for SpimDataMinimal

### ISSUE THREAD

**Issue by StephanPreibisch** [bigdataviewer/bigdataviewer-core#7]
Hi @tpietzsch,

I just realized that the constructor for the BigDataViewer is for SpimDataMinimal and not for AbstractSpimData. Is there a good reason for that? It does prevent to instantiate the BigDataViewer on an already opened AbstractSpimData object, which is for example SpimData or SpimData2 and hence does not extend SpimDataMinimal.

Thanks a lot!!

**Comment by tpietzsch** [comment]
@StephanPreibisch No reason for that. I'll change it to ```AbstractSpimData< ? >```

**Comment by StephanPreibisch** [comment]
The other option is something like that maybe:

public class SpimDataWrapper extends SpimDataMinimal
{
	/**
	 * create copy of a {@link SpimDataMinimal} with replaced {@link BasicImgLoader}
	 */
	public SpimDataWrapper( final SpimData2 other )
	{
		super(
				other.getBasePath(),
				new SequenceDescriptionMinimal(
						other.getSequenceDescription().getTimePoints(),
						other.getSequenceDescription().getViewSetups(),
						other.getSequenceDescription().getImgLoader(),
						other.getSequenceDescription().getMissingViews() ),
				other.getViewRegistrations() );
	}
}

**Comment by tpietzsch** [comment]
@StephanPreibisch no, no, I like AbstractSpimData better

**Comment by StephanPreibisch** [comment]
Awesome, thanks so much Tobi! Can you maybe make a new release with that change right away?

**Comment by tpietzsch** [comment]
Ok. I released bigdataviewer-core 1.0.7
http://maven.imagej.net/index.html#nexus-search;gav~~bigdataviewer-core~1.0.7~~

**Comment by StephanPreibisch** [comment]
Thanks @tpietzsch!
