### ISSUE TITLE
Release the HDF5 merge code?

### ISSUE THREAD

**Issue by StephanPreibisch** [bigdataviewer/bigdataviewer-core#8]
Hi @tpietzsch,

can we release the new version that supports HDF5 appending so I can release a new version of SPIM_Registration?

Thanks so much,
Stephan

**Comment by tpietzsch** [comment]
@StephanPreibisch is this still an open issue? What do you mean by HDF5 appending?

**Comment by StephanPreibisch** [comment]
That is a little outdated now, this was your new feature of appending HDF5 during fusion :)

**Comment by tpietzsch** [comment]
ah, ok :)
