### ISSUE TITLE
How to read affine transformation's line in xml?

### ISSUE THREAD

**Issue by maximka48** [bigdataviewer/bigdataviewer-core#88]
Hi all

Could you tell me how to read the affine transformation's line in the xml file of bdv? I read through the https://arxiv.org/pdf/1412.0488.pdf but couldn't find the answer.

I have six XYZ datasets inside my bdv .h5 file. Its xml description has 12 numbers at the Affine transformation's line. I assume that I should have at least 3 angles + 3 translations. Could you help me to figure which is which.

Thank you

**Comment by tpietzsch** [comment]
The 12 numbers at the Affine transformation's line are arranged in the upper 3x4 matrix of the 4x4 homogeneous affine transformation matrix.
```
a11 a12 a13 a14
a21 a22 a23 a24
a31 a32 a33 a34
  0   0   0   1
```
The coefficients appear in the xml in row major order, as `a11 a12 a13 a14 a21 a22 a23 a24 a31 a32 a33 a34`.

You can best think of the as forming a 3x3 matrix
```
    [a11 a12 a13]
A = [a21 a22 a23]
    [a31 a32 a33]
```
and 3-vector
```
    [a14]
b = [a24]
    [a34]
```
that transform coordinates `x` to coordinates `x'` as
```
x` = Ax + b
```
The multiplication by `A` is a combination of anisotropic scaling, rotation, and shear.
This is followed by translation `b`.

To If you require rotation angles etc, you need to extract them out of `A`.
BDV has some helper methods in [Affine3DHelpers](https://github.com/bigdataviewer/bigdataviewer-core/blob/60f622f92d1ccda9584ca796d8bc70fa2b485b66/src/main/java/bdv/util/Affine3DHelpers.java). (If that is not sufficient, just google for "extract rotation matrix from transformation matrix" or similar.)
